### ISSUE TITLE
BMP file

### ISSUE THREAD

**Issue by charlyms** [davidrainford/zeta_machine#1]
Hello Mr. Drainford,
I tried to generate some fractal images both on Fedora and Windows 7 according to the user_guide.txt.
I get some BMP files but each one is "incomplete" in a way.
Do you have an idea what is going wrong?
Regards from Germany 
![zm -99 101 -100 100 10 15 0 0](https://cloud.githubusercontent.com/assets/13423741/16349032/8363105e-3a56-11e6-97c6-e57b39a8adea.jpg)

![zmi 0 2 -1 1 1000 15 0 0](https://cloud.githubusercontent.com/assets/13423741/16348996/3a60d74c-3a56-11e6-94fd-1a8acfaf75d8.jpg)

Sorry, I had to convert the files to jpg.
Regards from Germany 
Charlyms

**Comment by davidrainford** [comment]
Hi Klaus

Thanks for trying this software! Yours is the first email I have received
about it! Sorry to hear you're getting unexpected results.

First, I recommend you only use it on Windows 7, 8 or 10. This is because
the BMP files are Windows format.

Second, please could you let me know which settings you tried. It looks
like you used a large real range and a small imaginary range. This won't
give you much fractal detail because all the interesting patterns are close
to the imaginary axis. I cannot explain the unusual colours you got.

Finally, please could you try an experiment for me? Please go to github and
download the precompiled Windows executable, the NTZ.db file and the
zeta_machine.text file. Then open the application and choose item 3 "Bulk
process" and let me know if you get good images.

I promise to do my best to help you!

Cheers

DR
On 24 Jun 2016 20:53, "Klaus Lang" <notifications@github.com> wrote:

Hello Mr. Drainford,
I tried to generate some fractal images both on Fedora and Windows 7
according to the user_guide.txt.
I get some BMP files but each one is "incomplete" in a way.
Do you have an idea what is going wrong?
Regards from Germany
[image: zm -99 101 -100 100 10 15 0 0]
<https://cloud.githubusercontent.com/assets/13423741/16348948/e2824362-3a55-11e6-8178-3bd4573f9b0a.jpg>

[image: zm -99 101 -100 100 10 15 0 0]
<https://cloud.githubusercontent.com/assets/13423741/16348948/e2824362-3a55-11e6-8178-3bd4573f9b0a.jpg>
Sorry, I had to convert the files to jpg.
Charlyms

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/davidrainford/zeta_machine/issues/1>, or mute the thread
<https://github.com/notifications/unsubscribe/AQIl0YhI4KOFOSARPFzwoF3wH3setJwEks5qPDXCgaJpZM4I-Exs>
.

**Comment by davidrainford** [comment]
Hi again Klaus

I have now had an opportunity to look more closely at your example image.

I can see that it covers the region of the complex plane between about -100
< Re(s) < 100 and -100 Im(s) -95 with a resolution of 10.

I note that there is a single line of black pixels at one edge which
suggests that this is a partially rendered image that has had the black
areas been cropped off. Perhaps the original image settings covered a much
greater area.

The level of detail is exactly as I would expect from a Resolution = 10
image.

What I cannot explain, however, is the colours. You will see from the
source code that the colour palettes are hardwired in the code. None of the
colours in the palettes falls within the indigo / lilac section of the
spectrum and yet your image shows these colours!

I have the following recommendations for using zeta_machine:

1. Please only us it with Windows because the application writes BMP files
in Windows format. Ideally, use the precompiled binary because I don't know
anything about compiler-induced issues.

2. Please use "." as the decimal point rather than "," when entering
decimanl parameters.

3. Please understand that image rendering is a *slow* process! Large high
resolution images take *days* to render, although any planned image can be
prototyped relatively quickly at a lower resolution.


I would love to make zeta_machine render its images faster, but I don't
think its speed can be improved by much. Every pixel requires multiple
approximations of the Riemann zeta function, and each such approximation
typically requires hundreds of individual complex number exponentions and
summations. These are all currently coded in C as efficiently as I think
they can be, so there is not much more that can be done. If you have any
ideas, I would be grateful!

I hope that you persist with zeta_machine and that you are eventually
successful in rendering fractal images.

Cheers

DR

**Comment by charlyms** [comment]
Hello,
at weekend I tried to run the bulk prozess on two machines, one Windows 7 64 bit, one Windows 10 64 bit.
Here are the results converted to jpg by Irfanview:
Win 7:
![zmi -24 20 -10 10 10 15 0 0 0 0 0 99 1](https://cloud.githubusercontent.com/assets/13423741/16393638/d176c12a-3cb1-11e6-8b00-5b63f604313a.jpg)
![zmi -24 20 -10 10 10 15 0 0](https://cloud.githubusercontent.com/assets/13423741/16393644/d4e65b22-3cb1-11e6-874d-7c404845c465.jpg)
Win 10:
![Uploading ZM -2, 5, 0, 50, 10, 15, 0, 0, 0, 0, 0.99, 2.jpg…]
![zm -2 5 0 50 10 15 1 1](https://cloud.githubusercontent.com/assets/13423741/16393670/f30b75ce-3cb1-11e6-9c3d-49169afa5ca1.jpg)
![zm -20 20 -10 10 10 15 0 0](https://cloud.githubusercontent.com/assets/13423741/16393677/f6b5870a-3cb1-11e6-9750-213c03b5e121.jpg)
Surprisingly Win 10 produced one more file!
Here´s another one from Win 10 it´s from prime patterns:
![zm 0 6 1 6 3109 3110 1000 15 0 0](https://cloud.githubusercontent.com/assets/13423741/16393898/de7b34fe-3cb2-11e6-8234-1207641a8202.jpg)
I forgotten how long the process of rendering lasts.
I am afraid my first pictures are indeed just incomplete!
Last idea: is it maybe possible to take the gpu for renedering?
Regards
Charlyms

**Comment by davidrainford** [comment]
Hi Klaus

Thank you for persisting with the experiment!

I can now see that the image rendering is working fine, maybe you just
interrupted the previous attempts a bit early.

I believe that I can now see what is happening in the colouring.

In the source code of *zeta_machine*, the individual bytes that make up the
red, blue and green channels are stored and processed in the order BLUE,
GREEN, RED which I think is normal practice in C.

In your images, however, the BLUE and RED channels are reversed. This may
be a hardware issue based on your processor architecture. The solution
would probably be to recompile the source code on your machine.

In the meantime, it is easy to convert your "wrongly" coloured images to
their "correct" colours by applying a hue adjustment of -124.

Please see attached recoloured versions of the key images that you uploaded
which I recoloured using *Paint.net <http://www.getpaint.net/index.html>*
with the following commands:

Select "Hue / Saturation..." from the "Adjustments" menu and move the "Hue"
slider to -124.

You will also achieve a much better image quality if you convert the BMP
files to PNG, but I think you knew that already!

I think you're right that rendering will be speeded-up if I were able to
access GPU processing power but, frankly, I wouldn't know where to start. I
will look into it.

Cheers

DR

**Comment by davidrainford** [comment]
Recoloured images:
![recolour](https://cloud.githubusercontent.com/assets/16917969/16396766/498e4056-3cb8-11e6-88f5-208e81bca7da.jpg)
![recolour2](https://cloud.githubusercontent.com/assets/16917969/16396767/49a6dcba-3cb8-11e6-9930-a33fbfeddcba.jpg)
![recolour3](https://cloud.githubusercontent.com/assets/16917969/16396768/49b2707a-3cb8-11e6-9994-413b43da5dd4.jpg)

**Comment by davidrainford** [comment]
Actually, the hue adjustment should be -127, not -124.

Cheers

DR
